---
- hosts: all
  sudo: true
  vars:
    web_server: apachephp
    servername: tradukoj.dev www.tradukoj.dev 10.10.10.8
    timezone: Europe/Madrid
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/apachephp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - apache
    - php5
    - mysql
    - composer
    - phpcommon
    - php-pecl
    - app
    - mrcrilly.mongodb
