---
- hosts: all
  sudo: true
  vars:
    web_server: apachephp
    servername: tradukoj.dev www.tradukoj.dev 10.10.10.8
    timezone: Europe/Madrid
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/apachephp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - apache
    - php5
    - mysql
    - composer
    - phpcommon
    - php-pecl
    - app
    - mrcrilly.mongodb

  tasks:
    - name: post install script
      shell: /vagrant/app/install.sh

#    - name: permissions on tmp
#      shell: sudo chmod -R 777 /tmp

    - name: Copying the conf of cli to apache
      shell: cp /etc/php5/cli/php.ini /etc/php5/apache2/php.ini
      sudo: yes

    - name:  "Restarting apache"
      sudo: yes
      shell:  service apache2 restart

    - name: if [ ! -e app/config/parameters.yml ]; then
      cp app/config/parameters.yml.dis app/config/parameters.yml
      fi

echo "Launching composer"
# Firing up composer. Better to invoke the INSTALL than an UPDATE
HOME=$(pwd) sh -c 'composer install --no-interaction'
echo "Creating MYSQL database"
# Creating database schema and tables
/usr/bin/env php app/console --no-interaction doctrine:database:drop --force
/usr/bin/env php app/console --no-interaction doctrine:database:create
/usr/bin/env php app/console --no-interaction doctrine:schema:create
# session pdo storage have to created by hand
mysql -u root -p'root' tradukoj < app/sessionpdo.sql
# fill language table with all languages
mysql -u root -p'root' tradukoj < app/languages.sql
echo "Creating MONGO database"
# creating user in mongo and create schema
echo 'db.addUser("tradukoj","tradukoj");' | mongo tradukoj
/usr/bin/env php app/console --no-interaction doctrine:mongodb:schema:create
echo "Assets & Assetic"
# Assets & Assetic
/usr/bin/env php app/console --no-interaction assets:install web --symlink
/usr/bin/env php app/console --no-interaction assetic:dump
echo "Creating first user and first project"
# Allowed fixtures go here
/usr/bin/env php app/console --no-interaction tradukoj:init:data
echo "Loading translations for the first project"
# Load first project
/usr/bin/env php app/console jlaso:translations:dump --force=yes
/usr/bin/env php app/console jlaso:translations:sync --upload-first=yes
